myproject/urls.py
# urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from GolfApp import views
from GolfApp.views import ParticipantCreateView
from GolfApp.views import ParticipantUpdateView


urlpatterns = [
    path('', views.index, name='index'),
    path('group_results/', views.group_results, name='group_results'),
    path('register/', views.ParticipantCreateView.as_view(), name='participant_register'),
    path('delete/', views.show_delete_participants_form, name='show_delete_participants_form'),
    path('delete_participants/', views.delete_participants, name='delete_participants'),
    path('participant/edit/<int:pk>/', ParticipantUpdateView.as_view(), name='participant_edit'),
    path('results/', views.result_list, name='result_list'),
    path('results/<int:result_id>/', views.result_detail, name='result_detail'),  # 詳細表示用のURL


]  # 他のURLパターン...

GolfApp/models.py
from django.db import models

class Participant(models.Model):
    name = models.CharField(max_length=100)
    kana_name = models.CharField(max_length=100, verbose_name='氏名カナ',default='')  # 氏名カナを追加
    average_score = models.IntegerField(default=0)  # FloatFieldからIntegerFieldに変更
    gender = models.CharField(max_length=1, choices=(('M', '男'), ('F', '女')))
    email = models.EmailField(max_length=254, verbose_name='メールアドレス', default='',blank=True)
    transportation = models.CharField(max_length=2, choices=(('Y', 'あり'), ('N', 'なし')), verbose_name='移動手段',default='N',blank=True)  # 移動手段を追加
    postal_code = models.CharField(max_length=8, verbose_name='郵便番号', default='',blank=True)  # 郵便番号
    prefecture = models.CharField(max_length=100, verbose_name='都道府県', default='',blank=True)  # 都道府県
    city = models.CharField(max_length=100, verbose_name='市区町村', default='',blank=True)  # 市区町村
    address = models.CharField(max_length=255, verbose_name='番地', default='',blank=True)  # 番地
    building = models.CharField(max_length=255, verbose_name='建物名', default='', blank=True)  # 建物名（任意）

    def __str__(self):
        return self.name
    
class GroupingResult(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    # その他、組分けに使用した条件などを保存するフィールド
    

class Group(models.Model):
    result = models.ForeignKey(GroupingResult, related_name='groups', on_delete=models.CASCADE)
    participants = models.ManyToManyField(Participant)

    def __str__(self):
        return f"Group {self.id} of {self.result.id}"
    

GolfApp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from .grouping import group_participants
from .models import Participant, GroupingResult, Group
from django.contrib import messages

class ParticipantCreateView(CreateView):
    model = Participant
    fields = ['name', 'kana_name', 'average_score', 'gender' , 'email', 'transportation', 'postal_code', 'prefecture', 'city', 'address', 'building']
    template_name = 'participant_form.html'
    success_url = reverse_lazy('index')

def index(request):
    if request.method == 'POST':
        selected_ids = request.POST.getlist('participants[]')
        print("選択された参加者ID:", selected_ids)
        selected_participants = Participant.objects.filter(id__in=selected_ids)
        if len(selected_participants) < 3:
            needed_participants = 3 - len(selected_participants)
            messages.error(request, f'参加者が足りません。あと{needed_participants}名の参加者が必要です。')
            return redirect('index')

        groups = group_participants(list(selected_participants))
        print(selected_participants)
        if any(len(group) < 3 for group in groups):
            messages.error(request, 'グループ分けに失敗しました。各グループは3名以上でなければなりません。')
            return redirect('index')

        grouping_result = GroupingResult()
        grouping_result.save()

        group_ids = []
        for group_members in groups:
            group = Group(result=grouping_result)
            group.save()
            for participant in group_members:
                group.participants.add(participant)
            group.save()
            group_ids.append(group.id)

        request.session['groups'] = group_ids  # セッションにグループIDを保存
        return redirect('group_results')
    else:
        participants = Participant.objects.all().order_by('kana_name')
        participant_count = participants.count()

        return render(request, 'index.html', {
            'participants': participants,
            'participant_count': participant_count
        })

def group_results(request):
    group_ids = request.session.get('groups', [])
    groups_with_sorted_participants = []
    for group_id in group_ids:
        group = Group.objects.get(id=group_id)
        sorted_participants = group.participants.all().order_by('average_score')
        groups_with_sorted_participants.append((group, sorted_participants))
   
    return render(request, 'group_results.html', {'groups_with_sorted_participants': groups_with_sorted_participants})

def delete_participants(request):
    if request.method == 'POST':
        selected_ids = request.POST.getlist('delete_participants[]')
        Participant.objects.filter(id__in=selected_ids).delete()
        messages.success(request, '選択された参加者を削除しました。')
    return redirect('index')

def show_delete_participants_form(request):
    participants = Participant.objects.all()
    return render(request, 'delete_participants.html', {'participants': participants})

class ParticipantUpdateView(UpdateView):
    model = Participant
    fields = ['name', 'kana_name', 'average_score', 'gender', 'email', 'transportation', 'postal_code', 'prefecture', 'city', 'address', 'building']
    template_name = 'participant_edit_form.html'
    success_url = reverse_lazy('index')

def result_list(request):
    results = GroupingResult.objects.all().order_by('-created_at')
    return render(request, 'grouping_result_list.html', {'results': results})

def result_detail(request, result_id):
    result = GroupingResult.objects.get(id=result_id)
    groups = result.groups.all()
    return render(request, 'grouping_result_detail.html', {'result': result, 'groups': groups})

def get_group_ids(grouping_result_id):
    group_ids = Group.objects.filter(result_id=grouping_result_id).values_list('id', flat=True)
    return list(group_ids)

GolfApp/templates/delete_participants.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>参加者削除</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>参加者削除</h1>
    <form action="{% url 'delete_participants' %}" method="post">
        {% csrf_token %}
        {% for participant in participants %}
        <div>
            <input type="checkbox" id="delete_participant{{ participant.id }}" name="delete_participants[]" value="{{ participant.id }}">
            <label for="delete_participant{{ participant.id }}">{{ participant.name }}</label>
        </div>
        {% endfor %}
        <button type="submit">選択した参加者を削除</button>
    </form>
    <a href="{% url 'index' %}">戻る</a>
</body>
</html>

GolfApp/templates/group_results.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>グループ分け結果</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>グループ分け結果</h1>
    {% for group, sorted_participants in groups_with_sorted_participants %}
        <h2>グループ {{ forloop.counter }}</h2>
        <ul>
        {% for participant in sorted_participants %}
            <!-- 最小スコアの参加者の名前の前に⛳️マークをつける -->
            <li>{% if forloop.first %}⛳️{% endif %}{{ participant.name }} - 平均スコア: {{ participant.average_score }}</li>
        {% endfor %}
        </ul>
    {% endfor %}
    <a href="{% url 'index' %}">戻る</a>
</body>
</html>

GolfApp/templates/grouping_result_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>組分け結果の詳細</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>組分け結果の詳細</h1>
    <h2>結果作成日時: {{ result.created_at|date:"Y年m月d日 H:i" }}</h2>
    {% for group in groups %}
        <h3>グループ {{ forloop.counter }}</h3>
        <ul>
            {% for participant in group.participants.all %}
                <li>{{ participant.name }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
    <a href="{% url 'result_list' %}">結果の一覧に戻る</a>
</body>
</html>

GolfApp/templates/grouping_result_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>組分け結果の一覧</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>組分け結果の一覧</h1>
    <ul>
        {% for result in results %}
            <li>
                <a href="{% url 'result_detail' result.id %}">組分け結果 {{ result.created_at|date:"Y年m月d日 H:i" }}</a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'index' %}">ホームに戻る</a>
</body>
</html>

GolfApp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>ゴルフコンペ参加者一覧</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>ゴルフコンペ参加者一覧</h1>

    <!-- 全選択・選択解除ボタンの追加 -->
    <div>
        <button type="button" id="selectAll">すべて選択</button>
        <button type="button" id="deselectAll">選択を解除</button>
        <a href="{% url 'participant_register' %}" class="btn btn-primary">参加者の新規登録</a>
        <a href="{% url 'show_delete_participants_form' %}" class="btn btn-primary">参加者の削除</a>
        <a href="{% url 'result_list' %}" class="btn">組分け結果の一覧を見る</a>
    </div>
    <div id="selectedCount">選択された参加者の人数: 0</div>
    <div>登録されているメンバーの人数: {{ participant_count }}</div>

    <form action="{% url 'index' %}" method="post">
        {% csrf_token %}
        <table class="participant-list">
            <thead>
                <tr>
                    <th></th> <!-- チェックボックス用のヘッダー -->
                    <th>名前</th>
                    <th>性別</th>
                    <th>平均スコア</th>
                    <th>クルマ</th>

                </tr>
            </thead>
            <tbody>
                {% for participant in participants %}
                <tr>
                    <td><input type="checkbox" name="participants[]" value="{{ participant.id }}"></td>
                    <!-- 名前をクリック可能にし、クリックしたら編集ページへ遷移するようにする -->
                    <td><a href="{% url 'participant_edit' participant.id %}" style="color: inherit; text-decoration: none;">{{ participant.name }}</a>{% if participant.is_etiquette_leader %}⛳️{% endif %}</td>
                    <td>{% if participant.gender == 'M' %}男性{% elif participant.gender == 'F' %}女性{% else %}その他{% endif %}</td>
                    <td>{{ participant.average_score }}</td>
                    <td>
                        {% if participant.transportation == 'Y' %}
                            <span style="font-size: 24px;">🚗</span>
                        {% endif %}
                    </td>
                    <td>
                        <!-- 編集ボタンを削除 -->
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">グループ分け実行</button>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const updateSelectedCount = () => {
                const selectedCount = document.querySelectorAll('input[type="checkbox"][name="participants[]"]:checked').length;
                document.getElementById('selectedCount').textContent = `選択された参加者の人数: ${selectedCount}`;
            };
        
            // すべて選択・選択解除ボタンのイベントリスナーに人数更新機能を追加
            document.getElementById('selectAll').addEventListener('click', function() {
                document.querySelectorAll('input[type="checkbox"][name="participants[]"]').forEach(function(checkbox) {
                    checkbox.checked = true;
                });
                updateSelectedCount(); // 人数を更新
            });
        
            document.getElementById('deselectAll').addEventListener('click', function() {
                document.querySelectorAll('input[type="checkbox"][name="participants[]"]').forEach(function(checkbox) {
                    checkbox.checked = false;
                });
                updateSelectedCount(); // 人数を更新
            });
        
            // 各チェックボックスの状態変更時に人数を更新
            document.querySelectorAll('input[type="checkbox"][name="participants[]"]').forEach(function(checkbox) {
                checkbox.addEventListener('change', updateSelectedCount);
            });
        
            // 初期状態での人数更新
            updateSelectedCount();
        });
        </script>
</body>
</html>

GolfApp/templates/participant_edit_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>参加者登録</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
          // 住所検索ボタンのクリックイベントを設定
          $('#address-search').on('click', function() {
            var postalCode = $('#id_postal_code').val().replace('-', ''); // ハイフンを除去
            if(postalCode.length === 7){
                $.ajax({
                url: "https://api.zipaddress.net/?zipcode=" + postalCode,
                dataType: 'jsonp',
                success: function(data) {
                    // 成功時の処理を修正
                    // data.code === 200 のチェックを削除
                    $('#id_prefecture').val(data.pref);
                    $('#id_city').val(data.city);
                    $('#id_address').val(data.town);
                    // デバッグ用：成功したレスポンスの内容をコンソールに出力
                    console.log("成功したレスポンス:", data);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    // エラー時の処理
                    console.log("リクエスト失敗:", textStatus, errorThrown);
                }
            });
            }
            return false; // フォーム送信を防ぐ
          });
        });
        </script>
</head>
<body>
    <h1>参加者編集</h1>
    <form method="post">
        {% csrf_token %}
        <!-- 名前 -->
        <p>
            <label for="id_name">名前:</label>
            {{ form.name }}
        </p>
        <!-- 氏名カナ -->
        <p>
            <label for="id_kana_name">氏名カナ:</label>
            {{ form.kana_name }}
        </p>

        <p>
            <label for="id_postal_code">郵便番号:</label>
            {{ form.postal_code }}
            <button id="address-search" type="button">住所検索</button> <!-- 住所検索ボタンを追加 -->
        </p>
        <!-- 都道府県 -->
        <p>
            <label for="id_prefecture">都道府県:</label>
            {{ form.prefecture }}
        </p>
        <!-- 市区町村 -->
        <p>
            <label for="id_city">市区町村:</label>
            {{ form.city }}
        </p>
        <!-- 番地 -->
        <p>
            <label for="id_address">それ以降の住所:</label>
            {{ form.address }}
        </p>
        <!-- 建物名 -->
        <p>
            <label for="id_building">建物名:</label>
            {{ form.building }}
        </p>
        <!-- スコア -->
        <p>
            <label for="id_average_score">平均スコア:</label>
            {{ form.average_score }}
        </p>
        <!-- 性別 -->
        <p>
            <label for="id_gender">性別:</label>
            {{ form.gender }}
        </p>

        <!-- メールアドレス -->
        <p>
            <label for="id_email">メールアドレス:</label>
            {{ form.email }}
        </p>
        <!-- 移動手段 -->
        <p>
            <label for="id_transportation">移動手段:</label>
            {{ form.transportation }}
        </p>

        <button type="submit">更新</button>
    </form>
    <a href="{% url 'index' %}">戻る</a>
</body>
</html>

GolfApp/templates/participant_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>参加者登録</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
        $(document).ready(function(){
          // 住所検索ボタンのクリックイベントを設定
          $('#address-search').on('click', function() {
            var postalCode = $('#id_postal_code').val().replace('-', ''); // ハイフンを除去
            if(postalCode.length === 7){
                $.ajax({
                url: "https://api.zipaddress.net/?zipcode=" + postalCode,
                dataType: 'jsonp',
                success: function(data) {
                    // 成功時の処理を修正
                    // data.code === 200 のチェックを削除
                    $('#id_prefecture').val(data.pref);
                    $('#id_city').val(data.city);
                    $('#id_address').val(data.town);
                    // デバッグ用：成功したレスポンスの内容をコンソールに出力
                    console.log("成功したレスポンス:", data);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    // エラー時の処理
                    console.log("リクエスト失敗:", textStatus, errorThrown);
                }
            });
            }
            return false; // フォーム送信を防ぐ
          });
        });
        </script>
    </head>
    <body>
    <h1>参加者登録</h1>
    <form method="post">
        {% csrf_token %}
        <!-- 名前 -->
        <p>
            <label for="id_name">名前:</label>
            {{ form.name }}
        </p>
        <!-- 氏名カナ -->
        <p>
            <label for="id_kana_name">氏名カナ:</label>
            {{ form.kana_name }}
        </p>

        <p>
            <label for="id_postal_code">郵便番号:</label>
            {{ form.postal_code }}
            <button id="address-search" type="button">住所検索</button> <!-- 住所検索ボタンを追加 -->
        </p>
        <!-- 都道府県 -->
        <p>
            <label for="id_prefecture">都道府県:</label>
            {{ form.prefecture }}
        </p>
        <!-- 市区町村 -->
        <p>
            <label for="id_city">市区町村:</label>
            {{ form.city }}
        </p>
        <!-- 番地 -->
        <p>
            <label for="id_address">それ以降の住所:</label>
            {{ form.address }}
        </p>
        <!-- 建物名 -->
        <p>
            <label for="id_building">建物名:</label>
            {{ form.building }}
        </p>
        <!-- スコア -->
        <p>
            <label for="id_average_score">平均スコア:</label>
            {{ form.average_score }}
        </p>
        <!-- 性別 -->
        <p>
            <label for="id_gender">性別:</label>
            {{ form.gender }}
        </p>
        <!-- メールアドレス -->
        <p>
            <label for="id_email">メールアドレス:</label>
            {{ form.email }}
        </p>
        <!-- 移動手段 -->
        <p>
            <label for="id_transportation">移動手段:</label>
            {{ form.transportation }}
        </p>
        <button type="submit">登録</button>
    </form>
</body>
</html>